name: Validate build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Install wasm-tools workload
        run: dotnet workload install wasm-tools

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test -c Release --no-build

  wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
      - uses: actions/checkout@v7

      - name: Build homebrew
        run: make -C wii

  n64:
    runs-on: ubuntu-latest
    container: ghcr.io/dragonminded/libdragon:latest
    steps:
      - uses: actions/checkout@v7

      - name: Build ROM
        run: sh n64/build.sh
